# Generated by Django 3.2.9 on 2022-08-29 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sfname', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم الاول ')),
                ('Smname', models.CharField(blank=True, max_length=50, null=True, verbose_name='الاب')),
                ('Slname', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجد')),
                ('Sidnumber', models.PositiveBigIntegerField(unique=True, verbose_name='الرقم القومي')),
                ('Spercent', models.IntegerField(default=0, verbose_name='نسبة الطالب ')),
                ('Spercenthomeworks', models.IntegerField(default=0, verbose_name='نسبة حل الواجبات')),
                ('Spercentexams', models.IntegerField(default=0, verbose_name='نسبة حل الامتحانات')),
                ('shomeworks', models.IntegerField(default=0, verbose_name=' حل الواجبات')),
                ('sexams', models.IntegerField(default=0, verbose_name=' حل الامتحانات')),
                ('points', models.BigIntegerField(default=10, verbose_name='النقاط')),
                ('finishExam', models.ManyToManyField(blank=True, to='tasks.exam', verbose_name='الإمتحانات التي تم ارسالها')),
                ('finishedHomework', models.ManyToManyField(blank=True, related_name='homework', to='home.Lessons', verbose_name='الواجبات التي تم ارسالها')),
                ('sinit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('watchedlecs', models.ManyToManyField(blank=True, related_name='wathedlecs', to='home.Lessons', verbose_name='المحاضرات المنتهيه')),
            ],
            options={
                'verbose_name': 'الطالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
    ]
