# Generated by Django 3.2.9 on 2022-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_sidnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sidnumber',
            field=models.PositiveBigIntegerField(default=1, unique=True, verbose_name='الرقم القومي'),
            preserve_default=False,
        ),
    ]
