# Generated by Django 3.2.9 on 2023-08-23 03:04

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_sidnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='simg',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student.upprofimg, verbose_name='صورة الطالب'),
        ),
    ]
