# Generated by Django 3.2.9 on 2023-08-23 20:03

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_simg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='simg',
            field=models.ImageField(upload_to=students.models.student.upprofimg, verbose_name='صورة الطالب'),
        ),
    ]
