# Generated by Django 3.2.9 on 2024-07-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_simg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sstatus',
            field=models.BooleanField(default=1, verbose_name='حالة الطالب'),
            preserve_default=False,
        ),
    ]
