# Generated by Django 4.2.14 on 2024-08-01 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_catgory_cimage_alter_catgory_name'),
        ('students', '0006_student_sstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Scourses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.catgory', verbose_name=''),
            preserve_default=False,
        ),
    ]
