# Generated by Django 4.2.14 on 2024-08-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_scourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Scourses',
        ),
    ]
