# Generated by Django 4.2.14 on 2024-08-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_catgory_cimage_alter_catgory_name'),
        ('students', '0010_remove_student_scourses_student_scourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Scourses',
            field=models.ManyToManyField(blank=True, related_name='Scourses', to='home.catgory', verbose_name='كورسات الطالب'),
        ),
    ]
