# Generated by Django 4.2.14 on 2024-08-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_scourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Sstatus',
            field=models.BooleanField(default=False, verbose_name='حالة الطالب'),
        ),
    ]
