# Generated by Django 4.2.14 on 2024-08-12 07:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_sstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sphone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='واتساب الطالب'),
        ),
    ]
