# Generated by Django 5.0.7 on 2025-01-10 18:52

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_sphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='simg',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student.upprofimg, verbose_name='صورة الطالب'),
        ),
    ]
