# Generated by Django 4.2.14 on 2025-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_simg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='SinitDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاريخ الإشتراك'),
        ),
    ]
