# Generated by Django 4.2.14 on 2025-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_sinitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Sidgroup',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='رقم المجموعه'),
        ),
    ]
