# Generated by Django 4.2.14 on 2025-02-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_sidgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Sidgroup',
        ),
        migrations.RemoveField(
            model_name='student',
            name='SinitDate',
        ),
    ]
