# Generated by Django 4.2.14 on 2025-02-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_views'),
        ('students', '0018_student_sinitdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='likenews',
            field=models.ManyToManyField(to='news.news', verbose_name='الأخبار المعجب بها'),
        ),
    ]
