# Generated by Django 4.2.14 on 2025-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_likes_alter_news_pupat'),
        ('students', '0019_student_likenews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='likenews',
            field=models.ManyToManyField(editable=False, to='news.news', verbose_name='الأخبار المعجب بها'),
        ),
    ]
