# Generated by Django 3.2.9 on 2023-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='العنوان')),
                ('img', models.ImageField(blank=True, null=True, upload_to='./img', verbose_name='صورة الإعلان')),
                ('detail', models.TextField(verbose_name='تفاصيل الإعلان')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'إعلانات',
            },
        ),
    ]
