# Generated by Django 3.2.9 on 2024-07-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'إعلان', 'verbose_name_plural': 'إعلانات'},
        ),
    ]
