# Generated by Django 4.2.14 on 2025-02-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pupAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='كلمة مفتاحيه'),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, verbose_name='عدد مشاهدات الإعلان'),
        ),
    ]
