# Generated by Django 4.2.14 on 2025-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_pupat_news_tags_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, editable=False, verbose_name='عدد إعجابات بالإعلان'),
        ),
    ]
