# Generated by Django 4.2.14 on 2025-02-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='عدد مشاهدات الإعلان'),
        ),
    ]
