# Generated by Django 4.2.14 on 2025-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='عدد إعجابات بالإعلان'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pupAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
