"""
Django settings for saskeproject project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
#import django_heroku

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rw&i-9a)9ch=%%6xg4sshp1x$*+(imzh&wox5cr@i*#obhe59c'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True 


#TEMPLATE_DEBUG = DEBUG
# ADMINS = (
#     ('saske', 'saskecompany1@gmail.com'),
# )

# MANAGERS = ADMINS

# if DEBUG:
ALLOWED_HOSTS = ['*']
# else:
# ALLOWED_HOSTS = ['www.tafawoq.online']


# Application definition

INSTALLED_APPS = [
    "whitenoise.runserver_nostatic",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'home',
    'news',
    'students',
    'tasks',
    'reports',
    'pay',
    'live',
    'coaches',
    "phonenumber_field",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'DjangoRangeMiddleware.midleware.RangesMiddleware',
]

ROOT_URLCONF = 'saskeproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/ "templates", BASE_DIR/ "home/templates/home", BASE_DIR/ "students/templates/students", BASE_DIR/ "tasks/templates/tasks", BASE_DIR/"reports/templates/reports", BASE_DIR/"pay/templates/pay", BASE_DIR / "news/templates/news", BASE_DIR / "live/templates/live", BASE_DIR / "coaches/templates/coaches"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.students_allpages.cuser',
                'home.students_allpages.searchV'
            ],
        },
    },
]

# WSGI_APPLICATION = 'saskeproject.wsgi.application'
ASGI_APPLICATION = 'saskeproject.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'sacadtest',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#         'OPTIONS': {
#             'charset': 'utf8mb4',
#             'collation': 'utf8mb4_unicode_ci',
#         },
#     },
# }
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ar-eg'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
# WHITENOISE_KEEP_ONLY_HASHED_FILES=True

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR/ "templates/static", 
    BASE_DIR/"tasks/static",
    BASE_DIR/ "reports/static",
    BASE_DIR/ "news/styles",
    BASE_DIR/ "students/styles",
]

STATIC_ROOT = BASE_DIR/ "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT = BASE_DIR/ 'media'
MEDIA_URL = '/media/'


#________________________________redirects
LOGIN_URL = "student/login"
LOGIN_REDIRECT_URL = '/'


# gmail_sending
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'saskecompany1@gmail.com'
EMAIL_HOST_PASSWORD = 'fopebdjfxpzrfrqg'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'default from email'


# if not DEBUG:
#     django_heroku.settings(locals(), staticfiles=False)


#     SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#     SECURE_SSL_REDIRECT = True

#     DEBUG_PROPAGATE_EXCEPTIONS = True
#     COMPRESS_ENABLED = os.environ.get('COMPRESS_ENABLED', False)
