# Generated by Django 3.2.9 on 2022-08-29 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='examReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asknumber', models.IntegerField(blank=True, null=True, verbose_name='عدد الاسئله')),
                ('correctAnswers', models.IntegerField(blank=True, null=True, verbose_name='الاجابات الصحيحه')),
                ('wrongAnswers', models.IntegerField(blank=True, null=True, verbose_name='الإجابات الخاطئه')),
                ('presentage', models.IntegerField(blank=True, null=True, verbose_name='النسبه المئويه')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.exam', verbose_name='امتحان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تقرير الامتحان',
                'verbose_name_plural': 'تقارير الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='homeworkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asknumber', models.IntegerField(blank=True, null=True, verbose_name='عدد الاسئله')),
                ('correctAnswers', models.IntegerField(blank=True, null=True, verbose_name='الاجابات الصحيحه')),
                ('wrongAnswers', models.IntegerField(blank=True, null=True, verbose_name='الإجابات الخاطئه')),
                ('presentage', models.IntegerField(blank=True, null=True, verbose_name='النسبه المئويه')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons', verbose_name='واجب درس')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تفرير الواجب',
                'verbose_name_plural': 'تقاربر الواجب',
            },
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examReport', models.ManyToManyField(blank=True, to='reports.examReport', verbose_name='امتحانات الطالب')),
                ('homerport', models.ManyToManyField(blank=True, to='reports.homeworkReport', verbose_name='واجبات الطالب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'التفرير',
                'verbose_name_plural': 'التقارير',
            },
        ),
    ]
