# Generated by Django 4.2.14 on 2025-02-03 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examreport',
            options={'verbose_name': 'تقرير امتحان', 'verbose_name_plural': 'تقارير الامتحانات'},
        ),
        migrations.AlterModelOptions(
            name='homeworkreport',
            options={'verbose_name': 'تقرير واجب', 'verbose_name_plural': 'تقاربر الواجب'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'التقرير', 'verbose_name_plural': 'التقارير'},
        ),
    ]
