# Generated by Django 3.2.9 on 2023-09-01 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=256, verbose_name='اسم اللايف')),
                ('Lurl', models.URLField(verbose_name='رابط اللايف')),
                ('Limg', models.ImageField(blank=True, null=True, upload_to='live images', verbose_name='صورة اللايف')),
                ('Linit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='منشيئ اللايف')),
            ],
        ),
    ]
