# Generated by Django 3.2.9 on 2023-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='Lroom',
            field=models.CharField(default=2, max_length=256, verbose_name='رقم الغرفه'),
            preserve_default=False,
        ),
    ]
