# Generated by Django 3.2.9 on 2023-09-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_alter_live_lurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='Lurl',
            field=models.URLField(verbose_name='رابط اللايف'),
        ),
    ]
