# Generated by Django 3.2.9 on 2023-09-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_alter_live_lurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='Lurl',
            field=models.TextField(verbose_name='رابط اللايف'),
        ),
    ]
