# Generated by Django 3.2.9 on 2024-07-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_alter_live_lurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='live',
            options={'verbose_name': 'بث', 'verbose_name_plural': 'قائمة البث المباشر'},
        ),
    ]
