# Generated by Django 3.2.9 on 2022-08-29 01:44

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم التصنيف')),
                ('cimage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='شعار التصنيف ان وجد')),
            ],
            options={
                'verbose_name': 'الفرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='اسم الحصه')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الحصه')),
                ('video', models.FileField(upload_to=home.models.Lessons.upleson, verbose_name='الحصه')),
                ('limg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة مصغره للحلقه')),
                ('catname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.catgory', verbose_name='يتبع')),
            ],
            options={
                'verbose_name': 'الدرس',
                'verbose_name_plural': 'الدروس',
            },
        ),
    ]
