# Generated by Django 3.2.9 on 2022-08-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catgory',
            name='cimage',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='limg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة مصغره للحلقه', width_field=200),
        ),
    ]
