# Generated by Django 3.2.9 on 2022-08-29 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220829_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='limg',
        ),
    ]
