# Generated by Django 3.2.9 on 2022-08-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_lessons_limg'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='شعار التصنيف ان وجد', width_field=200),
        ),
        migrations.AddField(
            model_name='lessons',
            name='limg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة مصغره للحلقه', width_field=200),
        ),
    ]
