# Generated by Django 3.2.9 on 2022-08-29 15:03

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220829_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgory',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.catgory.upcatimg, verbose_name='شعار التصنيف ان وجد'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='limg',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.Lessons.uplesonimg, verbose_name='صورة مصغره للحلقه'),
        ),
    ]
