# Generated by Django 3.2.9 on 2024-07-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('home', '0005_auto_20220829_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catgory',
            options={'verbose_name': 'الكورس', 'verbose_name_plural': 'الكورسات'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-date'], 'verbose_name': 'المحاضره', 'verbose_name_plural': 'المحاضرات'},
        ),
        migrations.AddField(
            model_name='catgory',
            name='CCoach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach', verbose_name='مدرب الكورس'),
        ),
    ]
