# Generated by Django 3.2.9 on 2024-07-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20240730_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='Cprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='قيمة الإشتراك شهري'),
        ),
    ]
