# Generated by Django 3.2.9 on 2024-07-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20240730_1951'),
        ('home', '0007_catgory_cprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgory',
            name='CCoach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coaches.coach', verbose_name='مدرب الكورس'),
        ),
    ]
