# Generated by Django 4.2.14 on 2024-08-01 15:06

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_catgory_ccoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgory',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.catgory.upcatimg, verbose_name='لوجو الكورس ان وجد'),
        ),
        migrations.AlterField(
            model_name='catgory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم الكورس'),
        ),
    ]
