# Generated by Django 4.2.14 on 2024-08-01 21:24

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_catgory_cimage_alter_catgory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=home.models.Lessons.upleson, verbose_name='الحصه'),
        ),
    ]
