# Generated by Django 4.2.14 on 2024-08-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_lessons_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='Youtube',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='لينك الحلقه من اليوتيوب'),
        ),
    ]
