# Generated by Django 4.2.14 on 2024-08-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_lessons_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='Youtube',
            new_name='LYoutube',
        ),
    ]
