# Generated by Django 4.2.14 on 2025-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_youtube_lessons_lyoutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='Crate',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐⭐', max_length=50, verbose_name='مستوي المدرب'),
        ),
    ]
