# Generated by Django 4.2.14 on 2025-02-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_catgory_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='Lviews',
            field=models.IntegerField(default=0, verbose_name='عدد مشاهدات الدرس'),
        ),
    ]
