# Generated by Django 4.2.14 on 2025-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_lessons_lviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='catgory',
            name='LHlevel',
            field=models.CharField(choices=[('سهل', 1), ('متوسط', 2), ('صعب', 3)], default=2, max_length=10, verbose_name='مستوي الواجبات'),
        ),
        migrations.AddField(
            model_name='catgory',
            name='Llevel',
            field=models.CharField(choices=[('سهل', 1), ('متوسط', 2), ('صعب', 3)], default=2, max_length=10, verbose_name='مستوي الواجبات'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='تاريخ الحصه'),
        ),
    ]
