# Generated by Django 4.2.14 on 2025-02-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_catgory_lhlevel_catgory_llevel_alter_lessons_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catgory',
            name='LHlevel',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='متوسط', max_length=10, verbose_name='مستوي الواجبات'),
        ),
        migrations.AlterField(
            model_name='catgory',
            name='Llevel',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='متوسط', max_length=10, verbose_name='مستوي الواجبات'),
        ),
    ]
