# Generated by Django 4.2.14 on 2025-02-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_catgory_lhlevel_alter_catgory_llevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catgory',
            name='LHlevel',
        ),
        migrations.RemoveField(
            model_name='catgory',
            name='Llevel',
        ),
        migrations.AddField(
            model_name='lessons',
            name='LHlevel',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='متوسط', max_length=10, verbose_name='مستوي الواجبات'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='Llevel',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='متوسط', max_length=10, verbose_name='مستوي الواجبات'),
        ),
    ]
