# Generated by Django 3.2.9 on 2024-07-30 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.TextField(verbose_name='اسم المدرب')),
                ('CPhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'المدرب',
                'verbose_name_plural': 'المدربين',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
