# Generated by Django 3.2.9 on 2024-07-30 16:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='CName',
            field=models.CharField(max_length=50, verbose_name='اسم المدرب'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='CPhone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='رقم المدرب'),
        ),
    ]
