# Generated by Django 3.2.9 on 2024-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20240730_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='Cemail',
            field=models.EmailField(default=1, max_length=254, verbose_name='بريد المدرب'),
            preserve_default=False,
        ),
    ]
