# Generated by Django 5.0.7 on 2025-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coach_cemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='Crate',
            field=models.CharField(choices=[('نجمه واحده', 1), ('نجمتان', 2), ('ثلاث نجوم', 3), ('اربع نجوم', 4), ('خمس نجوم', 5)], default=5, max_length=50, verbose_name='مستوي المدرب'),
        ),
    ]
