# Generated by Django 5.0.7 on 2025-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0004_coach_crate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='Crate',
            field=models.IntegerField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default=5, verbose_name='مستوي المدرب'),
        ),
    ]
