# Generated by Django 4.2.14 on 2025-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0005_alter_coach_crate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='Crate',
            field=models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐⭐', max_length=50, verbose_name='مستوي المدرب'),
        ),
    ]
