# Generated by Django 4.2.14 on 2025-02-01 19:01

import coaches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0006_alter_coach_crate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='Cimg',
            field=models.ImageField(blank=True, null=True, upload_to=coaches.models.coach.Cimage_Up, verbose_name='الصوره الشخصيه'),
        ),
    ]
