# Generated by Django 5.0.7 on 2025-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, choices=[(1, 'الاجابه الاولي'), (2, 'الاجابه الثانيه'), (3, 'الاجابه الثالثه'), (4, 'الاجابه الرابعه')], max_length=50, null=True, verbose_name='الاجابه الصحيحه'),
        ),
    ]
