# Generated by Django 4.2.14 on 2025-02-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(blank=True, choices=[('1', 'الاجابه الاولي'), ('2', 'الاجابه الثانيه'), ('3', 'الاجابه الثالثه'), ('4', 'الاجابه الرابعه')], max_length=50, null=True, verbose_name='الاجابه الصحيحه'),
        ),
    ]
