# Generated by Django 4.2.14 on 2025-02-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_catgory_crate'),
        ('tasks', '0003_alter_task_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.catgory', verbose_name='الماده'),
        ),
    ]
