# Generated by Django 4.2.14 on 2025-02-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_exam_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='views',
            field=models.IntegerField(default=0, verbose_name='عدد مشاهدات الإمتحان'),
        ),
    ]
