# Generated by Django 4.2.14 on 2025-02-05 23:31

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_exam_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='eximg',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.exam.examimg, verbose_name='صورة الإمتحان'),
        ),
    ]
