# Generated by Django 4.2.14 on 2025-02-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_exam_eximg'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('سهل', 1), ('متوسط', 2), ('صعب', 3)], default=2, max_length=10, verbose_name='مستوي الإمتحان'),
        ),
    ]
