# Generated by Django 4.2.14 on 2025-02-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_exam_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='level',
            field=models.CharField(choices=[('سهل', 'سهل'), ('متوسط', 'متوسط'), ('صعب', 'صعب')], default='متوسط', max_length=10, verbose_name='مستوي الإمتحان'),
        ),
    ]
